# Generated by Django 5.2.14 on 2026-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email_employee_joining_date_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[('Chennai', 'Chennai'), ('Vellore', 'Vellore'), ('Salem', 'Salem'), ('Kanchipuram', 'Kanchipuram'), ('Hosur', 'Hosur')], default='Chennai', max_length=100),
        ),
    ]
