# Generated by Django 5.2.13 on 2026-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_lat',
            field=models.FloatField(blank=True, help_text='Allowed work location latitude', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_lon',
            field=models.FloatField(blank=True, help_text='Allowed work location longitude', null=True),
        ),
    ]
