# Generated by Django 5.2.13 on 2026-05-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_work_lat_employee_work_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField(default=30)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('paid_days', models.DecimalField(decimal_places=1, default=30.0, max_digits=4)),
                ('gross_basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_child_edu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_personal_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earned_basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earned_hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earned_conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earned_child_edu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earned_personal_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_epf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_esi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_prof_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Generated', 'Generated'), ('Paid', 'Paid')], default='Generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
