# Generated by Django 5.2.13 on 2026-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0002_payslip_deduction_lwf_payslip_deduction_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='deduction_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_epf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='petrol_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
