# Generated by Django 5.2.13 on 2026-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tshirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='bank_proofs/')),
                ('photo_submitted', models.CharField(blank=True, max_length=10, null=True)),
                ('id_card_blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_aadhaar', models.BooleanField(default=False)),
                ('doc_pan', models.BooleanField(default=False)),
                ('doc_bank_proof', models.BooleanField(default=False)),
                ('doc_passport_photo', models.BooleanField(default=False)),
                ('doc_education_cert', models.BooleanField(default=False)),
                ('doc_resume', models.BooleanField(default=False)),
                ('doc_driving_license', models.BooleanField(default=False)),
                ('total_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('hp_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
