# Generated by Django 5.2.13 on 2026-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='doc_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_bank_proof',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/bank_proof/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_driving_license',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/driving_license/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_education_cert',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/education/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_pan',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/pan/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/passport/'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='doc_resume',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/resume/'),
        ),
    ]
