# Generated by Django 5.2.14 on 2026-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Late', 'Late'), ('overTime', 'overTime')], max_length=20),
        ),
    ]
