# Generated by Django 5.2.14 on 2026-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_intime_attendance_outtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Late', 'Late'), ('Overtime', 'Overtime')], max_length=20),
        ),
    ]
