# Generated by Codex on 2026-05-12

from django.db import migrations


def backfill_attendance_employee(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    Employee = apps.get_model("employees", "Employee")

    employees_by_name = {}
    for employee in Employee.objects.all():
        key = (employee.employee_name or "").strip().lower()
        if key and key not in employees_by_name:
            employees_by_name[key] = employee.id

    for record in Attendance.objects.filter(employee__isnull=True):
        key = (record.employee_name or "").strip().lower()
        employee_id = employees_by_name.get(key)
        if employee_id:
            record.employee_id = employee_id
            record.save(update_fields=["employee"])


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_attendance_employee"),
    ]

    operations = [
        migrations.RunPython(backfill_attendance_employee, migrations.RunPython.noop),
    ]
