# Generated by Codex on 2026-05-12

from django.db import migrations
from django.db.models import Q
from django.utils import timezone


def merge_daily_duplicates(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    Employee = apps.get_model("employees", "Employee")

    for employee in Employee.objects.all():
        records = Attendance.objects.filter(employee_id=employee.id).order_by("id")
        buckets = {}
        for r in records:
            dt = r.intime or r.outtime
            if not dt:
                continue
            day = timezone.localtime(dt).date() if timezone.is_aware(dt) else dt.date()
            buckets.setdefault(day, []).append(r)

        for _, day_records in buckets.items():
            if len(day_records) < 2:
                continue
            keep = day_records[0]
            for extra in day_records[1:]:
                if not keep.intime and extra.intime:
                    keep.intime = extra.intime
                if not keep.outtime and extra.outtime:
                    keep.outtime = extra.outtime
                if keep.status != "Present" and extra.status == "Present":
                    keep.status = "Present"
                keep.save()
                extra.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_backfill_attendance_employee"),
    ]

    operations = [
        migrations.RunPython(merge_daily_duplicates, migrations.RunPython.noop),
    ]
